# Add source files here
EXECUTABLE	:= DTreeCUDA

# CUDA source files (compiled with cudacc)
CUFILES		:= wrapper.cu

# C/C++ source files (compiled with gcc/c++)
CCFILESS	:= \
	model.cpp \
	program.cpp \

#Rules and targets
include ../../common/common.mk
